/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cashregister;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionListener;
import javax.swing.Action;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;



/**
 *
 * @author Dana
 */
public class main extends javax.swing.JFrame {
    
    private enum State { START, ITEMS, PAYMENT, PROCESSING, FINISHED }
    private State currentState = State.START;
    private JLabel statusLabel = new JLabel("READY");
    private String selectedPayment = "NONE";
    private double currentSubtotal = 0;
    private final double VAT_RATE = 0.12;
    private JLabel subtotalLabel = new JLabel("₱0.00");

    private JLabel statusDisplay = new JLabel("READY");

    private DefaultListModel<Product> inventoryModel = new DefaultListModel<>();
    private DefaultListModel<Product> selectedModel = new DefaultListModel<>();
    private JList<Product> inventoryList = new JList<>(inventoryModel);
    private JList<Product> selectedList = new JList<>(selectedModel);

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        setupApp();
        // test if connector successfully loads
         if (DBConnection.getConnection() != null) {
        System.out.println("Database Connected Successfully!");
    } else {
        System.out.println("Database Connection Failed!");
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        consoleSection = new javax.swing.JTextField();
        inventoryProducts = new javax.swing.JScrollPane();
        selectedProducts = new javax.swing.JScrollPane();
        rightContainer = new javax.swing.JPanel(new GridLayout (4, 3));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cash Register");
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(20, 18, 33));
        jPanel1.setFont(new java.awt.Font("Roboto Mono", 0, 12)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 700));

        consoleSection.setEditable(false);
        consoleSection.setBackground(new java.awt.Color(20, 18, 33));
        consoleSection.setFont(new java.awt.Font("Roboto Mono", 1, 48)); // NOI18N
        consoleSection.setForeground(new java.awt.Color(253, 119, 215));
        consoleSection.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        consoleSection.setText("CASH REGISTER");
        consoleSection.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 29, 47), 5, true));
        consoleSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consoleSectionActionPerformed(evt);
            }
        });

        inventoryProducts.setBackground(new java.awt.Color(20, 18, 33));
        inventoryProducts.setForeground(new java.awt.Color(255, 255, 255));

        selectedProducts.setBackground(new java.awt.Color(20, 18, 33));
        selectedProducts.setForeground(new java.awt.Color(255, 255, 255));

        rightContainer.setBackground(new java.awt.Color(20, 18, 33));
        rightContainer.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(consoleSection, javax.swing.GroupLayout.PREFERRED_SIZE, 925, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(inventoryProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(selectedProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rightContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(consoleSection, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inventoryProducts, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                    .addComponent(selectedProducts)
                    .addComponent(rightContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        consoleSection.getAccessibleContext().setAccessibleName("console");
        inventoryProducts.getAccessibleContext().setAccessibleName("inventory");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consoleSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consoleSectionActionPerformed

    }//GEN-LAST:event_consoleSectionActionPerformed

    private void setupApp() {
        inventoryProducts.setViewportView(inventoryList);
        selectedProducts.setViewportView(selectedList);
        inventoryList.setBackground(new java.awt.Color(20, 18, 33));
        inventoryList.setForeground(Color.WHITE);
        selectedList.setBackground(new java.awt.Color(20, 18, 33));
        selectedList.setForeground(new java.awt.Color(253, 119, 215));

        inventoryModel.clear();
        
        String query = "SELECT * FROM products"; 

        try (Connection conn = DBConnection.getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(query)) {

            while (rs.next()) {
                Product p = new Product(
                    rs.getInt("product_id"),
                    rs.getString("product_name"),
                    rs.getDouble("unit_price")
                );
                p.setQuantity(-1); 
                inventoryModel.addElement(p);
            }
        } catch (Exception e) {
            System.out.println("Error loading products: " + e.getMessage());
        }

        inventoryList.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                Product p = inventoryList.getSelectedValue();
                if (p != null) {
                boolean found = false;
                for (int i = 0; i < selectedModel.size(); i++) {
                    Product alreadyInList = selectedModel.getElementAt(i);
                    if (alreadyInList.getId() == p.getId()) {
                        // Increment quantity
                        alreadyInList.setQuantity(alreadyInList.getQuantity() + 1);

                        // Refresh the display in the JList
                        selectedModel.setElementAt(alreadyInList, i); 
                        found = true;
                        break;
                    }
                }

                if (!found) {
                    // Create a new instance so quantity changes don't affect the inventory list
                    Product newEntry = new Product(p.getId(), p.getName(), p.getPrice());
                    selectedModel.addElement(newEntry);
                }

                updateSubtotal();
                statusLabel.setText("ITEM ADDED");
                inventoryList.clearSelection();
                    /*selectedModel.addElement(p);
                    updateSubtotal();
                    statusLabel.setText("ITEM ADDED");
                    inventoryList.clearSelection();*/
                }
            }
        });
        
        // code to delete selected product
        selectedList.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                int index = selectedList.locationToIndex(e.getPoint());

                if (index != -1) {
                    Product p = selectedModel.getElementAt(index);

                   
                    int cellWidth = selectedList.getCellBounds(index, index).width;

                    if (e.getX() > cellWidth - 30) { 
                        selectedModel.remove(index);

                        updateSubtotal();
                        statusLabel.setText("ITEM REMOVED");
                    }
                }
            }
        });
        
        JPanel numpadGrid = new JPanel(new java.awt.GridLayout(4, 3, 5, 5));
        numpadGrid.setBackground(new java.awt.Color(20, 18, 33));

        numpadGrid.setLayout(new java.awt.GridLayout(4, 3, 5, 5));
        rightContainer.setBackground(new java.awt.Color(20, 18, 33));
        Color darkBg = new java.awt.Color(25, 23, 40);

        Action numberAction = new javax.swing.AbstractAction() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                if (consoleSection.getText().startsWith("TOTAL") || consoleSection.getText().equals("CASH REGISTER") || consoleSection.getText().startsWith("CHANGE")) {
                    consoleSection.setText(""); 
                }
                consoleSection.setText(consoleSection.getText() + e.getActionCommand());
            }
        };

        for (int i = 1; i <= 9; i++) {
            String val = String.valueOf(i);
            JButton btn = new JButton(val);
            btn.setActionCommand(val);
            btn.addActionListener(numberAction);
            styleButton(btn, darkBg); 
            numpadGrid.add(btn);
            bindKey("num"+val, java.awt.event.KeyEvent.VK_NUMPAD0+i, numberAction);
        }

        JButton btnBack = new JButton("X");
        btnBack.addActionListener(e -> {
            String txt = consoleSection.getText();
            if (txt.length() > 0) consoleSection.setText(txt.substring(0, txt.length()-1));
        });
        styleButton(btnBack, darkBg);
        btnBack.setForeground(Color.RED);
        numpadGrid.add(btnBack); 

        JButton btn0 = new JButton("0");
        btn0.setActionCommand("0");
        btn0.addActionListener(numberAction);
        styleButton(btn0, darkBg);
        numpadGrid.add(btn0);

        JButton btnEnter = new JButton("OK");
        btnEnter.addActionListener(e -> handleTransaction());
        styleButton(btnEnter, darkBg);
        btnEnter.setForeground(Color.GREEN);
        numpadGrid.add(btnEnter); 

        JPanel payPanel = new JPanel(new java.awt.GridLayout(1, 2, 5, 5));
        payPanel.setBackground(new java.awt.Color(20, 18, 33));
        JButton cashBtn = new JButton("CASH");
        JButton cardBtn = new JButton("CARD");
        styleButton(cashBtn, darkBg);
        styleButton(cardBtn, darkBg);

        java.awt.event.ActionListener payL = ex -> {
            selectedPayment = ex.getActionCommand();
            statusLabel.setText(selectedPayment + " SELECTED");
            if(selectedPayment.equals("CASH")) consoleSection.setText(""); 
        };
        cashBtn.addActionListener(payL);
        cardBtn.addActionListener(payL);
        payPanel.add(cashBtn);
        payPanel.add(cardBtn);

        JPanel thirdSection = new JPanel(new java.awt.BorderLayout(5, 8));
        thirdSection.setBackground(new java.awt.Color(20, 18, 33));
        
        JPanel topPanel = new JPanel(new GridLayout(2, 1, 5, 8));
        topPanel.setBackground(new java.awt.Color(20, 18, 33));
        
        JPanel statusConsole = new JPanel();
        statusConsole.setBackground(new java.awt.Color(30, 29, 47));
        statusConsole.setPreferredSize(new java.awt.Dimension(180, 100)); 
        statusConsole.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STATUS", 0, 0, null, new java.awt.Color(253, 119, 215)));

        statusLabel.setForeground(Color.WHITE);
        statusLabel.setHorizontalAlignment(SwingConstants.CENTER);
       
        statusConsole.add(statusLabel);
        
        JPanel subtotalConsole = new JPanel();
        subtotalConsole.setBackground(new java.awt.Color(30, 29, 47));
        subtotalConsole.setPreferredSize(new java.awt.Dimension(180, 100)); 
        subtotalConsole.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SUBTOTAL w/ VAT", 0, 0, null, new java.awt.Color(253, 119, 215)));
        
        
        subtotalLabel.setForeground(Color.WHITE);
        subtotalLabel.setHorizontalAlignment(SwingConstants.CENTER);
        subtotalLabel.setVerticalAlignment(SwingConstants.CENTER);
        subtotalLabel.setFont(new java.awt.Font("Roboto Mono", java.awt.Font.BOLD, 14));
        
        subtotalConsole.add(subtotalLabel);
        
        topPanel.add(statusConsole);
        topPanel.add(subtotalConsole);
        
        JPanel buttonPanel = new JPanel();
        buttonPanel.setLayout(new javax.swing.BoxLayout(buttonPanel, javax.swing.BoxLayout.Y_AXIS));
        buttonPanel.setBackground(new java.awt.Color(20, 18, 33));

        JButton receiptBtn = new JButton("RECEIPT");
        JButton recordsBtn = new JButton("RECORDS");
        JButton clearBtn = new JButton("CLEAR");
        JButton exitBtn = new JButton("EXIT");
        styleButton(receiptBtn, darkBg);
        styleButton(recordsBtn, darkBg);
        styleButton(clearBtn, darkBg);
        styleButton(exitBtn, darkBg);
        receiptBtn.setMaximumSize(new java.awt.Dimension(180, 35));
        recordsBtn.setMaximumSize(new java.awt.Dimension(180, 35));
        clearBtn.setMaximumSize(new java.awt.Dimension(180, 35));
        exitBtn.setMaximumSize(new java.awt.Dimension(180, 35));
        
        buttonPanel.add(receiptBtn);
        buttonPanel.add(javax.swing.Box.createVerticalStrut(8));
        buttonPanel.add(recordsBtn);
        buttonPanel.add(javax.swing.Box.createVerticalStrut(8));
        buttonPanel.add(clearBtn);
        buttonPanel.add(javax.swing.Box.createVerticalStrut(8));
        buttonPanel.add(exitBtn);
        
        // logic for clear button
        clearBtn.addActionListener(e -> {
            selectedModel.clear();
            updateSubtotal();
            statusLabel.setText("LIST CLEARED");
        });
        
        // for exit button
        exitBtn.addActionListener(e -> {
            System.exit(0);
        });
        
        thirdSection.add(topPanel, BorderLayout.NORTH);
        thirdSection.add(buttonPanel, BorderLayout.SOUTH);

       JPanel rightGroup = new JPanel(new java.awt.BorderLayout(10, 10));
       rightGroup.setBackground(new java.awt.Color(20, 18, 33));
       rightGroup.setPreferredSize(new java.awt.Dimension(150, 350)); 
       rightGroup.add(numpadGrid, java.awt.BorderLayout.CENTER); 
       rightGroup.add(payPanel, java.awt.BorderLayout.SOUTH);


       JPanel finalRight = new JPanel(new java.awt.BorderLayout(10, 10));
       finalRight.setBackground(new java.awt.Color(20, 18, 33));
       finalRight.add(rightGroup, java.awt.BorderLayout.CENTER);
       finalRight.add(thirdSection, java.awt.BorderLayout.EAST);


       rightContainer.setLayout(new java.awt.BorderLayout());
       rightContainer.removeAll();
       rightContainer.add(finalRight, java.awt.BorderLayout.CENTER);
       rightContainer.revalidate();
       rightContainer.repaint();

    }


    private void updateSubtotal() {
        currentSubtotal = 0;
        for (int i = 0; i < selectedModel.size(); i++) {
            Product p = selectedModel.getElementAt(i);
            currentSubtotal += (p.getPrice() * p.getQuantity());
        }
        double totalWithVat = currentSubtotal * (1 + VAT_RATE);
        consoleSection.setText(String.format("TOTAL: ₱%.2f", currentSubtotal));
        subtotalLabel.setText(String.format("₱%.2f", totalWithVat));
    }

    private void handleTransaction() {
        if (selectedPayment.equals("NONE")) {
            statusLabel.setText("SELECT PAYMENT!");
            return;
        }

        double totalDue = currentSubtotal * (1 + VAT_RATE);

        if (selectedPayment.equals("CASH")) {
            try {
                double paid = Double.parseDouble(consoleSection.getText());
                if (paid < totalDue) {
                    statusLabel.setText("LACKING CASH!");
                    return;
                }
                double change = paid - totalDue;
                consoleSection.setText(String.format("CHANGE: ₱%.2f", change));
            } catch (Exception e) { statusLabel.setText("INVALID CASH"); return; }
        }

        statusLabel.setText("PROCESSING...");

        javax.swing.Timer timer = new javax.swing.Timer(3000, e -> {
            selectedModel.clear();
            consoleSection.setText("CASH REGISTER");
            statusLabel.setText("READY");
            selectedPayment = "NONE";
        });
        timer.setRepeats(false);
        timer.start();
    }


    //keyboard binder
    private void bindKey(String name, int keyCode, Action action) {
        rightContainer.getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW)
              .put(javax.swing.KeyStroke.getKeyStroke(keyCode, 0), name);
        rightContainer.getActionMap().put(name, action);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }
    
    private void styleButton(JButton btn, Color bgColor) {
    btn.setFont(new java.awt.Font("Roboto Mono", java.awt.Font.BOLD, 20));
    btn.setBackground(bgColor);
    btn.setForeground(new java.awt.Color(253, 119, 215)); // Your Pink Accent
    btn.setFocusPainted(false);
    btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 29, 47), 2));
    btn.setContentAreaFilled(false);
    btn.setOpaque(true);         
    btn.setFocusPainted(false);  
   
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField consoleSection;
    private javax.swing.JScrollPane inventoryProducts;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel rightContainer;
    private javax.swing.JScrollPane selectedProducts;
    // End of variables declaration//GEN-END:variables
}
